# Generated by Django 4.2.14 on 2024-09-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_alter_courses_options_alter_questions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(null=True),
        ),
    ]
